---
# K3s Agent handlers

- name: Restart k3s agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: restarted
    daemon_reload: true
  listen: restart k3s-agent

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd
